---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'grandtraining'
SiteConfig:
  extensions:
    - SiteConfigExtension
CourseHolder:
  allowed_children:
    - CoursePage
CoursePage:
  can_be_root: false
